# Generated by Django 3.2.5 on 2022-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('startdateplanned', models.DateField(blank=True, default=None, null=True)),
                ('completiondateplanned', models.DateField(blank=True, default=None, null=True)),
                ('completiondateactual', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
