# Generated by Django 3.2.5 on 2022-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completiondateactualtext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
